/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-03-23 01:33:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class right_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<HEAD id=Head1>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t<title>My JSP 'YHChannelApply.jsp' starting page</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t\t<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\t\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<META http-equiv=Content-Type content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t\t<LINK href=\"css/right/Style.css\" type=text/css rel=stylesheet>\r\n");
      out.write("\t\t<LINK href=\"css/right/Manage.css\" type=text/css rel=stylesheet>\r\n");
      out.write("\t\t<!--  <SCRIPT language=javascript src=\"try/right/FrameDiv.js\"></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\t\t<SCRIPT language=javascript src=\"try/right/Common.js\"></SCRIPT>-->\r\n");
      out.write("\r\n");
      out.write("\t\t<SCRIPT language=javascript>\r\n");
      out.write("        function selectallbox()\r\n");
      out.write("        {\r\n");
      out.write("            var list = document.getElementsByName('setlist');\r\n");
      out.write("            var listAllValue='';\r\n");
      out.write("             if(document.getElementById('checkAll').checked)\r\n");
      out.write("             {\r\n");
      out.write("                  for(var i=0;i<list.length;i++)\r\n");
      out.write("                  {\r\n");
      out.write("                    list[i].checked = true;\r\n");
      out.write("                    if(listAllValue=='')\r\n");
      out.write("                        listAllValue=list[i].value;\r\n");
      out.write("                    else\r\n");
      out.write("                        listAllValue = listAllValue + ',' + list[i].value;\r\n");
      out.write("                  }\r\n");
      out.write("                  document.getElementById('boxListValue').value=listAllValue;\r\n");
      out.write("             }\r\n");
      out.write("             else \r\n");
      out.write("             {\r\n");
      out.write("                  for(var i=0;i<list.length;i++)\r\n");
      out.write("                  {\r\n");
      out.write("                    list[i].checked = false;\r\n");
      out.write("                  }\r\n");
      out.write("                  document.getElementById('boxListValue').value='';\r\n");
      out.write("             }\r\n");
      out.write("         } \r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\t\t<META content=\"MSHTML 6.00.2900.3492\" name=GENERATOR>\r\n");
      out.write("\t</HEAD>\r\n");
      out.write("\t<BODY>\r\n");
      out.write("\t\t<FORM id=form1 name=form1\r\n");
      out.write("\t\t\tmethod=post>\r\n");
      out.write("\t\t\t<SCRIPT type=text/javascript>\r\n");
      out.write("//<![CDATA[\r\n");
      out.write("var theForm = document.forms['form1'];\r\n");
      out.write("if (!theForm) {\r\n");
      out.write("    theForm = document.form1;\r\n");
      out.write("}\r\n");
      out.write("function __doPostBack(eventTarget, eventArgument) {\r\n");
      out.write("    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {\r\n");
      out.write("        theForm.__EVENTTARGET.value = eventTarget;\r\n");
      out.write("        theForm.__EVENTARGUMENT.value = eventArgument;\r\n");
      out.write("        theForm.submit();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("//]]>\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<TABLE cellSpacing=0 cellPadding=0 width=\"101%\" border=0>\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD width=15>\r\n");
      out.write("\t\t\t\t\t\t\t<IMG src=\"img/right/new_019.jpg\" border=0>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"100%\" background=img/right/new_020.jpg height=20></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=15>\r\n");
      out.write("\t\t\t\t\t\t\t<IMG src=\"img/right/new_021.jpg\" border=0>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t<TABLE cellSpacing=0 cellPadding=0 width=\"101%\" height=\"92.5%\"\r\n");
      out.write("\t\t\t\tborder=0>\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD width=15 background=img/right/new_022.jpg>\r\n");
      out.write("\t\t\t\t\t\t\t<IMG src=\"img/right/new_022.jpg\" border=0>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD vAlign=top width=\"960\" height=\"550\" bgColor=#ffffff>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe src=\"index/iframe_background.jsp\" name=\"contentFrame\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight=\"100%\" width=\"1168\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=15 background=img/right/new_023.jpg>\r\n");
      out.write("\t\t\t\t\t\t\t<IMG src=\"img/right/new_023.jpg\" border=0>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t\t<TABLE cellSpacing=0 cellPadding=0 width=\"101%\" border=0>\r\n");
      out.write("\t\t\t\t<TBODY>\r\n");
      out.write("\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t<TD width=15>\r\n");
      out.write("\t\t\t\t\t\t\t<IMG src=\"img/right/new_024.jpg\" border=0>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t<TD align=middle width=\"100%\" background=img/right/new_025.jpg\r\n");
      out.write("\t\t\t\t\t\t\theight=15></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=15>\r\n");
      out.write("\t\t\t\t\t\t\t<IMG src=\"img/right/new_026.jpg\" border=0>\r\n");
      out.write("\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TBODY>\r\n");
      out.write("\t\t\t</TABLE>\r\n");
      out.write("\t\t</FORM>\r\n");
      out.write("\t</BODY>\r\n");
      out.write("</HTML>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
