/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-03-23 01:33:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\r\n");
      out.write("\t\t<title>欢迎来到建设银行开放式基金交易平台！</title>\r\n");
      out.write("\t\t<script language=\"javascript\">\r\n");
      out.write("\tfunction callStatus(){ \r\n");
      out.write("\t\tvar title=\"欢迎来到本站点！\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t//for(var i=1;i<=title.length;i++){\r\n");
      out.write("\t\t\t\tvar i=1;\r\n");
      out.write("\t\t\t\tintervalID= window.setInterval(function(){ //间隔n时间执行function（）函数\r\n");
      out.write("\t\t\t\t\tvar title1=title.substr(0,i);\t\r\n");
      out.write("\t\t\t\t\twindow.status=title1\r\n");
      out.write("\t\t\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\t\t\tvar timeStr=date.toLocaleString();\r\n");
      out.write("\t\t\t\t\t\twindow.status=title1+\"        \"+timeStr;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ti++;\r\n");
      out.write("\t\t\t\t\t\tif(i==9)\r\n");
      out.write("\t\t\t\t\t\ti=1;\r\n");
      out.write("\t\t\t\t},3000);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tcallStatus();\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t\t<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\t\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<frameset cols=\"*,1360,*\" border=\"0\" frameSpacing=\"0\" frameBorder=\"0\">\r\n");
      out.write("\t<frame src=\"about:blank\"></frame>\r\n");
      out.write("\t<FRAMESET frameSpacing=\"0\" rows=\"80,*\" style=\"width:1360;\">\r\n");
      out.write("\t\t<frame name=top src=\"index/top.jsp\" frameBorder=0 noResize\r\n");
      out.write("\t\t\tscrolling=no>\r\n");
      out.write("\t\t<FRAMESET frameSpacing=\"0\" cols=\"165,*\">\r\n");
      out.write("\t\t\t<FRAME name=menu src=\"index/left.jsp\" frameBorder=0 noResize>\r\n");
      out.write("\t\t\t<FRAME name=dmMain src=\"index/right.jsp\" frameBorder=0  scrolling=\"no\">\r\n");
      out.write("\t\t</FRAMESET>\r\n");
      out.write("\t</FRAMESET>\r\n");
      out.write("\t<frame src=\"about:blank\"></frame>\r\n");
      out.write("\t</frameset>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
