/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-03-30 01:03:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head id=\"Head1\">\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("BODY {\r\n");
      out.write("\tFONT-SIZE: 12px;\r\n");
      out.write("\tCOLOR: #ffffff;\r\n");
      out.write("\tFONT-FAMILY: 宋体\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("TD {\r\n");
      out.write("\tFONT-SIZE: 12px;\r\n");
      out.write("\tCOLOR: #ffffff;\r\n");
      out.write("\tFONT-FAMILY: 宋体\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\t\t<meta content=\"MSHTML 6.00.6000.16809\" name=\"GENERATOR\">\r\n");
      out.write("\t\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("                function validata()\r\n");
      out.write("                {\r\n");
      out.write("                \tvar adminname = document.getElementById(\"adminname\");\r\n");
      out.write("                \tvar adminpwd = document.getElementById(\"adminpwd\");\r\n");
      out.write("\t\t\t\t\tvar inputname = document.getElementById(\"inputname\");\r\n");
      out.write("\t\t\t\t\tvar inputpwd = document.getElementById(\"inputpwd\");\r\n");
      out.write("\t\t\t\t\tvar allinput = true;\r\n");
      out.write("\t\t\t\t\tif (!adminname.value || adminname.value == \"\")\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tallinput = false;\r\n");
      out.write("\t\t\t\t\t\tinputname.style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tinputname.style.visibility = \"hidden\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (!adminpwd.value || adminpwd.value == \"\")\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tallinput = false;\r\n");
      out.write("\t\t\t\t\t\tinputpwd.style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tinputpwd.style.visibility = \"hidden\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (allinput == true)\r\n");
      out.write("\t\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\t\tvar form1 = document.getElementById(\"form1\");\r\n");
      out.write("\t\t\t\t\t\tvar name = document.getElementById(\"name\");\r\n");
      out.write("\t\t\t\t\t\tvar pwd = document.getElementById(\"pwd\");\r\n");
      out.write("\t\t\t\t\t\tname.value = adminname.value;\r\n");
      out.write("\t\t\t\t\t\tpwd.value = adminpwd.value;\r\n");
      out.write("\t\t\t\t\t\tform1.submit();\r\n");
      out.write("\t\t\t\t\t\treturn true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("                }\r\n");
      out.write("       \t</script>\r\n");
      out.write("       \t<title>请登录</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<form id=\"form1\" action=\"Login\" method=\"post\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input id=\"name\" type=\"hidden\" name=\"name\">\r\n");
      out.write("\t\t\t\t<input id=\"pwd\" type=\"hidden\" name=\"pwd\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"UpdatePanel1\">\r\n");
      out.write("\t\t\t\t<div id=\"div1\"\r\n");
      out.write("\t\t\t\t\tstyle=\"LEFT: 0px; POSITION: absolute; TOP: 0px; BACKGROUND-COLOR: #0066ff\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"div2\"\r\n");
      out.write("\t\t\t\t\tstyle=\"LEFT: 0px; POSITION: absolute; TOP: 0px; BACKGROUND-COLOR: #0066ff\"></div>\r\n");
      out.write("\t\t\t\t<script language=\"JavaScript\" type=\"text/javascript\"> \r\n");
      out.write("\t\t\t\t\tvar speed=20;\r\n");
      out.write("\t\t\t\t\tvar temp=new Array(); \r\n");
      out.write("\t\t\t\t\tvar clipright=document.body.clientWidth/2,clipleft=0 \r\n");
      out.write("\t\t\t\t\tfor (i=1;i<=2;i++){ \r\n");
      out.write("\t\t\t\t\t\ttemp[i]=eval(\"document.all.div\"+i+\".style\");\r\n");
      out.write("\t\t\t\t\t\ttemp[i].width=document.body.clientWidth/2;\r\n");
      out.write("\t\t\t\t\t\ttemp[i].height=document.body.clientHeight;\r\n");
      out.write("\t\t\t\t\t\ttemp[i].left=(i-1)*parseInt(temp[i].width);\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\tfunction openit(){ \r\n");
      out.write("\t\t\t\t\t\tclipright-=speed;\r\n");
      out.write("\t\t\t\t\t\ttemp[1].clip=\"rect(0 \"+clipright+\" auto 0)\";\r\n");
      out.write("\t\t\t\t\t\tclipleft+=speed;\r\n");
      out.write("\t\t\t\t\t\ttemp[2].clip=\"rect(0 auto auto \"+clipleft+\")\";\r\n");
      out.write("\t\t\t\t\t\tif (clipright<=0)\r\n");
      out.write("\t\t\t\t\t\t\tclearInterval(tim);\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\ttim=setInterval(\"openit()\",100);\r\n");
      out.write("                </script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<table cellSpacing=\"0\" cellPadding=\"0\" width=\"900\" align=\"center\"\r\n");
      out.write("\t\t\t\t\t\tborder=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 105px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/login/login_1.gif\" border=0\"\" alt=\"\" width=\"900\" height=\"105\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td background=\"img/login/login_2.jpg\" height=\"300\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table height=\"300\" cellPadding=\"0\" width=\"900\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td colSpan=\"2\" height=\"35\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"360\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<table cellSpacing=\"0\" cellPadding=\"2\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 28px\" width=\"80\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t登 录 名：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 28px\" width=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"adminname\" style=\"WIDTH: 130px\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 28px\" width=\"370\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"inputname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"FONT-WEIGHT: bold; visibility: hidden; COLOR: white\">请输入登录名</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 28px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t登录密码：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 28px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"adminpwd\" style=\"WIDTH: 130px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 28px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"inputpwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"FONT-WEIGHT: bold; visibility: hidden; COLOR: white\">请输入密码</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 18px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 18px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"HEIGHT: 18px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonclick='return validata()' type=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"img/login/login_button.gif\" name=\"btn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/login/login_3.jpg\" border=\"0\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
