/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Printf */

#ifndef _Included_jni_Printf
#define _Included_jni_Printf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Printf
 * Method:    Print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_Printf_Print
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
